language: go
go:  
   - "1.8.x"
   - "1.9.x"
   - "1.10.x"
   - "1.11.x"
before_script: 
    - export GOPATH="$HOME/gopath"
    - go get -d -v
    - make prepare
    - "export LD_LIBRARY_PATH=$PWD/libgit2/install/lib"
    - "export PKG_CONFIG_PATH=$PWD/libgit2/install/lib/pkgconfig"
script: 
   - make test

jobs:
   include:
     - stage: "Build"
       name: "gitql build"
       script: make && ./gitql -v
